name: Release

on:
  push:
    branches: [ master ]


concurrency:
  group: tag-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: buckhamduffy/release-drafter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
